DROP TABLE IF EXISTS TAB_DES_WOM;

CREATE TABLE TAB_DES_WOM(
	IDT 		INTEGER NOT NULL AUTO_INCREMENT,
	IDT_WON		VARCHAR(15) NOT NULL,
	CONT 		VARCHAR(500) NOT NULL,
	ORD			INTEGER NOT NULL,
	TIP			VARCHAR(20) NOT NULL,
	PRIMARY KEY (IDT)
);